version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    environment:
      - PYTHONUNBUFFERED=1 # Optional: ensures Python output is streamed directly
    volumes:
      - ./tmp:/app/tmp 
